### ISSUE TITLE
Mouse scroll

### ISSUE THREAD

**Issue by Federico-Ciuffardi** [juliusHuelsmann/st-history#13]
Is there a way of scroll with the mouse?

**Comment by juliusHuelsmann** [comment]
No, that's not possible ever since the vim patch is based on the history patch that I also developed in this repository.

The old version of the vim-browse patch should theoretically support scrolling with the mouse after you apply the corresponding extension of the scrolllback patch, but that version of vim-browse is no longer maintained and might be more buggy than the current one.
